apiVersion: v1
kind: Secret
metadata:
  name: github-https-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/vinaya-repo/argocd-test-repo-1.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinaya-repo/argocd-test-repo-1.git
    targetRevision: HEAD  # Specify the desired branch or commit
    path: . # Path to the application within the repository
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server
    namespace: argocd  # Target namespace for deploying resources
